@namespace
class SpriteKind:
    Boss = SpriteKind.create()

def on_b_pressed():
    global Difficulty
    Difficulty = 1
    music.play(music.melody_playable(music.ba_ding),
        music.PlaybackMode.UNTIL_DONE)
controller.B.on_event(ControllerButtonEvent.PRESSED, on_b_pressed)

def on_on_overlap(sprite2, otherSprite2):
    game.game_over(False)
    game.set_game_over_scoring_type(game.ScoringType.HIGH_SCORE)
    if randint(0, 10) == 1:
        game.show_long_text("It's estimated seafood lovers eat 11,000 pieces of toxic plastic every year.",
            DialogLayout.FULL)
    elif randint(0, 10) == 2:
        game.show_long_text("1 in 3 fish for human consumption contains plastic.",
            DialogLayout.FULL)
    elif randint(0, 10) == 3:
        game.show_long_text("Microplastic can be found in tap water and salt.",
            DialogLayout.FULL)
    elif randint(0, 10) == 4:
        game.show_long_text("Numerous chemicals used to produce plastic are known to be carcinogenic and to interfere with the body's hormone system causing reproductive, neurological, and immune disorders in both humans and wildlife.",
            DialogLayout.FULL)
    elif randint(0, 10) == 5:
        game.show_long_text("Excessive marine pollution has helped create 500 dead zones (the size of the United Kingdom's surface (245,000 km²) in the ocean – this number will double every decade.",
            DialogLayout.FULL)
    elif randint(0, 10) == 6:
        game.show_long_text("70% of Earth's oxygen is produced by marine plants AND 30% of our CO2 emissions are absorbed by the oceans.",
            DialogLayout.FULL)
    elif randint(0, 10) == 7:
        game.show_long_text("18 billion pounds of plastic pollution flows into the sea from coastal regions yearly.",
            DialogLayout.FULL)
    elif randint(0, 10) == 8:
        game.show_long_text("Only 10 river systems contribute to 90% of the plastic that flows into the sea.",
            DialogLayout.FULL)
    elif randint(0, 10) == 9:
        game.show_long_text("500 billion plastic bottles are used every year – Meaning there are 66 times as many bottles as there are humans on the planet.",
            DialogLayout.FULL)
    elif randint(0, 10) == 10:
        game.show_long_text("A plastic bottle can last for 450 years in the marine environment.",
            DialogLayout.FULL)
    else:
        game.show_long_text("Hi, who ever is looking at the code, it's currently 3:30am",
            DialogLayout.FULL)
sprites.on_overlap(SpriteKind.player, SpriteKind.enemy, on_on_overlap)

def on_on_overlap2(sprite, otherSprite):
    game.game_over(False)
    game.set_game_over_scoring_type(game.ScoringType.HIGH_SCORE)
    if randint(0, 10) == 1:
        game.show_long_text("14% of all litter is from drinks containers.",
            DialogLayout.FULL)
    elif randint(0, 10) == 2:
        game.show_long_text("Less than half of the bottles bought in 2016 were recycled.",
            DialogLayout.FULL)
    elif randint(0, 10) == 3:
        game.show_long_text("Scientists estimate 7.5 million straws pollute US coastlines & between 437 million to 8.3 billion plastic straws on coastlines around the world.",
            DialogLayout.FULL)
    elif randint(0, 10) == 4:
        game.show_long_text("Up to one trillion plastic bags are used worldwide each year – that's 160,000 a second.",
            DialogLayout.FULL)
    elif randint(0, 10) == 5:
        game.show_long_text("It can take anything between 20-1000 years for a plastic bag to break up.",
            DialogLayout.FULL)
    elif randint(0, 10) == 6:
        game.show_long_text("Plastics consistently make up 60 to 90% of all marine debris studied.",
            DialogLayout.FULL)
    elif randint(0, 10) == 7:
        game.show_long_text("20% of all plastic waste in the sea comes from marine sources such as nets, ropes, and lines.",
            DialogLayout.FULL)
    elif randint(0, 10) == 8:
        game.show_long_text("60% of the materials that form clothing are forms of plastic (Nylon, acrylic, polyester, etc). Your typical clothes wash will produce around 700,000 microplastic fibers.",
            DialogLayout.FULL)
    elif randint(0, 10) == 9:
        game.show_long_text("Marine plastic pollution has affected 100% of marine turtles, 59% of whales, 36% of seals and 40% of seabirds of those examined.",
            DialogLayout.FULL)
    elif randint(0, 10) == 10:
        game.show_long_text("Over 1 million seabirds and 100,000 marine mammals are killed by ocean plastic every year.",
            DialogLayout.FULL)
    else:
        game.show_long_text("Hi, who ever is looking at the code, it's currently 3:30am",
            DialogLayout.FULL)
sprites.on_overlap(SpriteKind.player, SpriteKind.projectile, on_on_overlap2)

def on_combos_attach_combo():
    for index in range(100000000):
        music.play(music.melody_playable(music.ba_ding),
            music.PlaybackMode.IN_BACKGROUND)
controller.combos.attach_combo("uuddlrlrba", on_combos_attach_combo)

projectile: Sprite = None
Difficulty = 0
game.set_dialog_text_color(15)
game.show_long_text("Every day ~8 million pieces of trash make its way into our oceans. This number is set to double by 2034. Let's see how life is like for a fish in the modern day ocean. Use WASD or the arrow keys or move and avoid getting caught in garbage or by a predator.",
    DialogLayout.FULL)
info.set_score(0)
scene.set_background_image(assets.image("""
    myImage
"""))
Fish = sprites.create(img("""
        . . . . . . . . . . . . . . . . 
            . . . . . . . . c c c c . . . . 
            . . . . . . c c d d d d c . . . 
            . . . . . c c c c c c d c . . . 
            . . . . c c 4 4 4 4 d c c . . . 
            . . . c 4 d 4 4 4 4 4 1 c . c c 
            . . c 4 4 4 1 4 4 4 4 d 1 c 4 c 
            . c 4 4 4 4 1 4 4 4 4 4 1 c 4 c 
            f 4 4 4 4 4 1 4 4 4 4 4 1 4 4 f 
            f 4 4 4 f 4 1 c c 4 4 4 1 f 4 f 
            f 4 4 4 4 4 1 4 4 f 4 4 d f 4 f 
            . f 4 4 4 4 1 c 4 f 4 d f f f f 
            . . f f 4 d 4 4 f f 4 c f c . . 
            . . . . f f 4 4 4 4 c d b c . . 
            . . . . . . f f f f d d d c . . 
            . . . . . . . . . . c c c . . .
    """),
    SpriteKind.player)
controller.move_sprite(Fish, 100, 100)
Bottle_1 = sprites.create(assets.image("""
    Bottle 1
"""), SpriteKind.enemy)
Bottle_2 = sprites.create(img("""
        ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            .....7977777777.....
            .....7777777777.....
            ......66666666......
            ......99999999......
            .....9999999999.....
            .....9999999999.....
            .....9999999999.....
            .....7777777777.....
            .....7777777777.....
            .....7777777776.....
            .....7777777776.....
            ......76666666......
            ....................
            ....................
    """),
    SpriteKind.enemy)
Bottle_3 = sprites.create(img("""
        ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ........4eee........
            .......eeeeee.......
            .........cc.........
            .........4c.........
            ........4444........
            .......444444.......
            ......44444444......
            .....4444444444.....
            .....eeeeeeeeee.....
            .....eeeeeeeecc.....
            ......eeeeeecc......
            .......eccccc.......
            ....................
            ....................
    """),
    SpriteKind.enemy)
Bottle_4 = sprites.create(img("""
        ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ........dd55........
            ........5555........
            .........44.........
            ........dddd........
            ........dddd........
            .......dddddd.......
            .......dddddd.......
            .......dddddd.......
            .......dddddd.......
            .......dddddd.......
            .......dddddd.......
            ........dddd........
            ........4444........
            ....................
    """),
    SpriteKind.enemy)
Bottle_5 = sprites.create(img("""
        ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            .........888........
            .........888........
            ......888888888.....
            ........fffff.......
            .......8888888......
            .......8998888......
            .......8988888......
            .......8888888......
            .......8888888......
            .......8888888......
            ......888888888.....
            ......fffffffff.....
            ....................
            ....................
    """),
    SpriteKind.enemy)
Bottle_1.set_position(randint(5, 160), 0)
Bottle_1.set_velocity(0, 100)
Bottle_2.set_position(0, 0)
Bottle_3.set_position(0, 0)
Bottle_4.set_position(0, 0)
Bottle_5.set_position(0, 0)
animation.run_image_animation(Fish,
    [img("""
            . . . . . . . . . . . . . . . . 
                . . . . . . . . c c c c . . . . 
                . . . . . . c c d d d d c . . . 
                . . . . . c c c c c c d c . . . 
                . . . . c c 4 4 4 4 d c c . . . 
                . . . c 4 d 4 4 4 4 4 1 c . c c 
                . . c 4 4 4 1 4 4 4 4 d 1 c 4 c 
                . c 4 4 4 4 1 4 4 4 4 4 1 c 4 c 
                f 4 4 4 4 4 1 4 4 4 4 4 1 4 4 f 
                f 4 4 4 f 4 1 c c 4 4 4 1 f 4 f 
                f 4 4 4 4 4 1 4 4 f 4 4 d f 4 f 
                . f 4 4 4 4 1 c 4 f 4 d f f f f 
                . . f f 4 d 4 4 f f 4 c f c . . 
                . . . . f f 4 4 4 4 c d b c . . 
                . . . . . . f f f f d d d c . . 
                . . . . . . . . . . c c c . . .
        """),
        img("""
            . . . . . . . . . . . . . . . . 
                . . . . . . . c c c c c . . . . 
                . . . . . . c d d d d d c . . . 
                . . . . . . c c c c c d c . . . 
                . . . . . c 4 4 4 4 d c c . . . 
                . . . . c d 4 4 4 4 4 1 c . . . 
                . . . c 4 4 1 4 4 4 4 4 1 c . . 
                . . c 4 4 4 4 1 4 4 4 4 1 c c c 
                . c 4 4 4 4 4 1 c c 4 4 1 4 4 c 
                . c 4 4 4 4 4 1 4 4 f 4 1 f 4 f 
                f 4 4 4 4 f 4 1 c 4 f 4 d f 4 f 
                f 4 4 4 4 4 4 1 4 f f 4 f f 4 f 
                . f 4 4 4 4 1 4 4 4 4 c b c f f 
                . . f f f d 4 4 4 4 c d d c . . 
                . . . . . f f f f f c c c . . . 
                . . . . . . . . . . . . . . . .
        """),
        img("""
            . . . . . . . . c c c c . . . . 
                . . . . . . c c d d d d c . . . 
                . . . . . c c c c c c d c . . . 
                . . . . c c 4 4 4 4 d c c . c c 
                . . . c 4 d 4 4 4 4 4 1 c c 4 c 
                . . c 4 4 4 1 4 4 4 4 d 1 c 4 f 
                . c 4 4 4 4 1 4 4 4 4 4 1 4 4 f 
                f 4 4 4 4 4 1 1 c f 4 4 1 f 4 f 
                f 4 4 4 f 4 1 c 4 f 4 4 1 f 4 f 
                f 4 4 4 4 4 1 4 4 f 4 4 d f f f 
                . f 4 4 4 4 1 c c 4 4 d f f . . 
                . . f f 4 d 4 4 4 4 4 c f . . . 
                . . . . f f 4 4 4 4 c d b c . . 
                . . . . . . f f f f d d d c . . 
                . . . . . . . . . . c c c . . . 
                . . . . . . . . . . . . . . . .
        """),
        img("""
            . . . . . . . . . . . . . . . . 
                . . . . . . . . . c c c c . . . 
                . . . . . . . c c d d d d c . . 
                . . . . . c c c c c c d d c . . 
                . . . c c c 4 4 4 4 d c c c c c 
                . . c 4 4 1 4 4 4 4 4 1 c c 4 f 
                . c 4 4 4 4 1 4 4 4 4 d 1 f 4 f 
                f 4 4 4 4 4 1 4 4 4 4 4 1 f 4 f 
                f 4 4 f 4 4 1 4 c f 4 4 1 4 4 f 
                f 4 4 4 4 4 1 c 4 f 4 4 1 f f f 
                . f 4 4 4 4 1 4 4 f 4 4 d f . . 
                . . f 4 4 1 4 c c 4 4 d f . . . 
                . . . f d 4 4 4 4 4 4 c f . . . 
                . . . . f f 4 4 4 4 c d b c . . 
                . . . . . . f f f f d d d c . . 
                . . . . . . . . . . c c c . . .
        """)],
    150,
    True)

def on_update_interval():
    global projectile
    if Difficulty == 0:
        if info.score() >= 10:
            if randint(1, 10) <= 5:
                projectile = sprites.create_projectile_from_side(img("""
                        ..............fffcc.............
                                            ..............fcbddcc...........
                                            ...............fbbddcc..........
                                            ...............fcbbccf..........
                                            ..ccc.........ffccccccfffff.....
                                            ..cbbcc....fffcbbbbcbbbbbbbff...
                                            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                                            ...fbbdcfcccccbbbcbcbbffbbbbbbff
                                            ....fbbffcccccbbbbbcb1ff11bbbcbf
                                            ....fcbbcccccccbbbbb11111111bbbf
                                            ....fcccccccccccbbbb11cc33111bf.
                                            ...fcbbffbdbcccccbbb111c13cccf..
                                            ...fbbf..ccddddcfbbbc111c31cf...
                                            ..fbbf.....ccdccbbdbf111cccf....
                                            ..fff........ccbbdcfcccc........
                                            ..............fffff.............
                    """),
                    randint(10, 100),
                    0)
                projectile.set_position(0, randint(0, 160))
                animation.run_image_animation(projectile,
                    [img("""
                            ..............fffcc.............
                                                ..............fcbddcc...........
                                                ...............fbbddcc..........
                                                ...............fcbbccf..........
                                                ..ccc.........ffccccccfffff.....
                                                ..cbbcc....fffcbbbbcbbbbbbbff...
                                                ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                                                ...fbbdcfcccccbbbcbcbbffbbbbbbff
                                                ....fbbffcccccbbbbbcb1ff11bbbcbf
                                                ....fcbbcccccccbbbbb11111111bbbf
                                                ....fcccccccccccbbbb11cc33111bf.
                                                ...fcbbffbdbcccccbbb111c13cccf..
                                                ...fbbf..ccddddcfbbbc111c31cf...
                                                ..fbbf.....ccdccbbdbf111cccf....
                                                ..fff........ccbbdcfcccc........
                                                ..............fffff.............
                        """),
                        img("""
                            ..............fffcc.............
                                                ..............fbbddc............
                                                ...............fbbddc...........
                                                ccc............fcbbccf..........
                                                cbbcc.........ffccccccffffff....
                                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                                ..fccbcccccccccbbbbbb11111111bf.
                                                .fcbbfffccccccccbbbb11cc33cccf..
                                                .fbbf...cbdbcccccbbb111c131cf...
                                                fbbf.....ccdddddfbbbc111c33f....
                                                fff........ccddfbbdbf1111ff.....
                                                .............cfbbdbfccccc.......
                                                ..............fffff.............
                        """),
                        img("""
                            ..............fffc..............
                                                ..............fbddcc............
                                                ..ccc.........ffbddbc...........
                                                ..cbbc.........fcbbccf..........
                                                ...cbdc.......ffccccccfffffff...
                                                ...fbdc....fffcbbbbbbbbbbbbbcff.
                                                ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
                                                ....fcdffcccccbbbcbcbbbffbbbbcbf
                                                ....fcbbccccccbbbcbcbbbff1111bbf
                                                ...fcbbccccccccbbbcbb11111111bf.
                                                ...fbbfffcccccccbbbb11bc33cccf..
                                                ..fbbf..cbdbcccccbbb111c131cf...
                                                ..fff....cbdddddccbbc111c33f....
                                                ..........ccbddccbbdf1111ff.....
                                                ............ccfbbbdfccccc.......
                                                ..............fffff.............
                        """),
                        img("""
                            ..............fffcc.............
                                                ..............fbbddc............
                                                ...............fbbddc...........
                                                ccc............fcbbccf..........
                                                cbbcc.........ffccccccffffff....
                                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                                ..fccbcccccccccbbbbbb11111111bf.
                                                .fcbbfffccccccccbbbb11cc33cccf..
                                                .fbbf...cbdbcccccbbb111c131cf...
                                                fbbf.....ccdddddfbbbc111c33f....
                                                fff........ccddfbbdbf1111ff.....
                                                .............cfbbdbfccccc.......
                                                ..............fffff.............
                        """)],
                    150,
                    True)
        if info.score() >= 15:
            if randint(1, 10) <= 4:
                projectile = sprites.create_projectile_from_side(img("""
                        ..............fffcc.............
                                            ..............fcbddcc...........
                                            ...............fbbddcc..........
                                            ...............fcbbccf..........
                                            ..ccc.........ffccccccfffff.....
                                            ..cbbcc....fffcbbbbcbbbbbbbff...
                                            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                                            ...fbbdcfcccccbbbcbcbbffbbbbbbff
                                            ....fbbffcccccbbbbbcb1ff11bbbcbf
                                            ....fcbbcccccccbbbbb11111111bbbf
                                            ....fcccccccccccbbbb11cc33111bf.
                                            ...fcbbffbdbcccccbbb111c13cccf..
                                            ...fbbf..ccddddcfbbbc111c31cf...
                                            ..fbbf.....ccdccbbdbf111cccf....
                                            ..fff........ccbbdcfcccc........
                                            ..............fffff.............
                    """),
                    randint(10, 100),
                    0)
                projectile.set_position(0, randint(0, 160))
                animation.run_image_animation(projectile,
                    [img("""
                            ..............fffcc.............
                                                ..............fcbddcc...........
                                                ...............fbbddcc..........
                                                ...............fcbbccf..........
                                                ..ccc.........ffccccccfffff.....
                                                ..cbbcc....fffcbbbbcbbbbbbbff...
                                                ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                                                ...fbbdcfcccccbbbcbcbbffbbbbbbff
                                                ....fbbffcccccbbbbbcb1ff11bbbcbf
                                                ....fcbbcccccccbbbbb11111111bbbf
                                                ....fcccccccccccbbbb11cc33111bf.
                                                ...fcbbffbdbcccccbbb111c13cccf..
                                                ...fbbf..ccddddcfbbbc111c31cf...
                                                ..fbbf.....ccdccbbdbf111cccf....
                                                ..fff........ccbbdcfcccc........
                                                ..............fffff.............
                        """),
                        img("""
                            ..............fffcc.............
                                                ..............fbbddc............
                                                ...............fbbddc...........
                                                ccc............fcbbccf..........
                                                cbbcc.........ffccccccffffff....
                                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                                ..fccbcccccccccbbbbbb11111111bf.
                                                .fcbbfffccccccccbbbb11cc33cccf..
                                                .fbbf...cbdbcccccbbb111c131cf...
                                                fbbf.....ccdddddfbbbc111c33f....
                                                fff........ccddfbbdbf1111ff.....
                                                .............cfbbdbfccccc.......
                                                ..............fffff.............
                        """),
                        img("""
                            ..............fffc..............
                                                ..............fbddcc............
                                                ..ccc.........ffbddbc...........
                                                ..cbbc.........fcbbccf..........
                                                ...cbdc.......ffccccccfffffff...
                                                ...fbdc....fffcbbbbbbbbbbbbbcff.
                                                ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
                                                ....fcdffcccccbbbcbcbbbffbbbbcbf
                                                ....fcbbccccccbbbcbcbbbff1111bbf
                                                ...fcbbccccccccbbbcbb11111111bf.
                                                ...fbbfffcccccccbbbb11bc33cccf..
                                                ..fbbf..cbdbcccccbbb111c131cf...
                                                ..fff....cbdddddccbbc111c33f....
                                                ..........ccbddccbbdf1111ff.....
                                                ............ccfbbbdfccccc.......
                                                ..............fffff.............
                        """),
                        img("""
                            ..............fffcc.............
                                                ..............fbbddc............
                                                ...............fbbddc...........
                                                ccc............fcbbccf..........
                                                cbbcc.........ffccccccffffff....
                                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                                ..fccbcccccccccbbbbbb11111111bf.
                                                .fcbbfffccccccccbbbb11cc33cccf..
                                                .fbbf...cbdbcccccbbb111c131cf...
                                                fbbf.....ccdddddfbbbc111c33f....
                                                fff........ccddfbbdbf1111ff.....
                                                .............cfbbdbfccccc.......
                                                ..............fffff.............
                        """)],
                    150,
                    True)
        if info.score() >= 20:
            if randint(1, 10) <= 3:
                projectile = sprites.create_projectile_from_side(img("""
                        ..............fffcc.............
                                            ..............fcbddcc...........
                                            ...............fbbddcc..........
                                            ...............fcbbccf..........
                                            ..ccc.........ffccccccfffff.....
                                            ..cbbcc....fffcbbbbcbbbbbbbff...
                                            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                                            ...fbbdcfcccccbbbcbcbbffbbbbbbff
                                            ....fbbffcccccbbbbbcb1ff11bbbcbf
                                            ....fcbbcccccccbbbbb11111111bbbf
                                            ....fcccccccccccbbbb11cc33111bf.
                                            ...fcbbffbdbcccccbbb111c13cccf..
                                            ...fbbf..ccddddcfbbbc111c31cf...
                                            ..fbbf.....ccdccbbdbf111cccf....
                                            ..fff........ccbbdcfcccc........
                                            ..............fffff.............
                    """),
                    randint(10, 100),
                    0)
                projectile.set_position(0, randint(0, 160))
                animation.run_image_animation(projectile,
                    [img("""
                            ..............fffcc.............
                                                ..............fcbddcc...........
                                                ...............fbbddcc..........
                                                ...............fcbbccf..........
                                                ..ccc.........ffccccccfffff.....
                                                ..cbbcc....fffcbbbbcbbbbbbbff...
                                                ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                                                ...fbbdcfcccccbbbcbcbbffbbbbbbff
                                                ....fbbffcccccbbbbbcb1ff11bbbcbf
                                                ....fcbbcccccccbbbbb11111111bbbf
                                                ....fcccccccccccbbbb11cc33111bf.
                                                ...fcbbffbdbcccccbbb111c13cccf..
                                                ...fbbf..ccddddcfbbbc111c31cf...
                                                ..fbbf.....ccdccbbdbf111cccf....
                                                ..fff........ccbbdcfcccc........
                                                ..............fffff.............
                        """),
                        img("""
                            ..............fffcc.............
                                                ..............fbbddc............
                                                ...............fbbddc...........
                                                ccc............fcbbccf..........
                                                cbbcc.........ffccccccffffff....
                                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                                ..fccbcccccccccbbbbbb11111111bf.
                                                .fcbbfffccccccccbbbb11cc33cccf..
                                                .fbbf...cbdbcccccbbb111c131cf...
                                                fbbf.....ccdddddfbbbc111c33f....
                                                fff........ccddfbbdbf1111ff.....
                                                .............cfbbdbfccccc.......
                                                ..............fffff.............
                        """),
                        img("""
                            ..............fffc..............
                                                ..............fbddcc............
                                                ..ccc.........ffbddbc...........
                                                ..cbbc.........fcbbccf..........
                                                ...cbdc.......ffccccccfffffff...
                                                ...fbdc....fffcbbbbbbbbbbbbbcff.
                                                ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
                                                ....fcdffcccccbbbcbcbbbffbbbbcbf
                                                ....fcbbccccccbbbcbcbbbff1111bbf
                                                ...fcbbccccccccbbbcbb11111111bf.
                                                ...fbbfffcccccccbbbb11bc33cccf..
                                                ..fbbf..cbdbcccccbbb111c131cf...
                                                ..fff....cbdddddccbbc111c33f....
                                                ..........ccbddccbbdf1111ff.....
                                                ............ccfbbbdfccccc.......
                                                ..............fffff.............
                        """),
                        img("""
                            ..............fffcc.............
                                                ..............fbbddc............
                                                ...............fbbddc...........
                                                ccc............fcbbccf..........
                                                cbbcc.........ffccccccffffff....
                                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                                ..fccbcccccccccbbbbbb11111111bf.
                                                .fcbbfffccccccccbbbb11cc33cccf..
                                                .fbbf...cbdbcccccbbb111c131cf...
                                                fbbf.....ccdddddfbbbc111c33f....
                                                fff........ccddfbbdbf1111ff.....
                                                .............cfbbdbfccccc.......
                                                ..............fffff.............
                        """)],
                    150,
                    True)
        if info.score() >= 25:
            if randint(1, 10) <= 2:
                projectile = sprites.create_projectile_from_side(img("""
                        ..............fffcc.............
                                            ..............fcbddcc...........
                                            ...............fbbddcc..........
                                            ...............fcbbccf..........
                                            ..ccc.........ffccccccfffff.....
                                            ..cbbcc....fffcbbbbcbbbbbbbff...
                                            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                                            ...fbbdcfcccccbbbcbcbbffbbbbbbff
                                            ....fbbffcccccbbbbbcb1ff11bbbcbf
                                            ....fcbbcccccccbbbbb11111111bbbf
                                            ....fcccccccccccbbbb11cc33111bf.
                                            ...fcbbffbdbcccccbbb111c13cccf..
                                            ...fbbf..ccddddcfbbbc111c31cf...
                                            ..fbbf.....ccdccbbdbf111cccf....
                                            ..fff........ccbbdcfcccc........
                                            ..............fffff.............
                    """),
                    randint(10, 100),
                    0)
                projectile.set_position(0, randint(0, 160))
                animation.run_image_animation(projectile,
                    [img("""
                            ..............fffcc.............
                                                ..............fcbddcc...........
                                                ...............fbbddcc..........
                                                ...............fcbbccf..........
                                                ..ccc.........ffccccccfffff.....
                                                ..cbbcc....fffcbbbbcbbbbbbbff...
                                                ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                                                ...fbbdcfcccccbbbcbcbbffbbbbbbff
                                                ....fbbffcccccbbbbbcb1ff11bbbcbf
                                                ....fcbbcccccccbbbbb11111111bbbf
                                                ....fcccccccccccbbbb11cc33111bf.
                                                ...fcbbffbdbcccccbbb111c13cccf..
                                                ...fbbf..ccddddcfbbbc111c31cf...
                                                ..fbbf.....ccdccbbdbf111cccf....
                                                ..fff........ccbbdcfcccc........
                                                ..............fffff.............
                        """),
                        img("""
                            ..............fffcc.............
                                                ..............fbbddc............
                                                ...............fbbddc...........
                                                ccc............fcbbccf..........
                                                cbbcc.........ffccccccffffff....
                                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                                ..fccbcccccccccbbbbbb11111111bf.
                                                .fcbbfffccccccccbbbb11cc33cccf..
                                                .fbbf...cbdbcccccbbb111c131cf...
                                                fbbf.....ccdddddfbbbc111c33f....
                                                fff........ccddfbbdbf1111ff.....
                                                .............cfbbdbfccccc.......
                                                ..............fffff.............
                        """),
                        img("""
                            ..............fffc..............
                                                ..............fbddcc............
                                                ..ccc.........ffbddbc...........
                                                ..cbbc.........fcbbccf..........
                                                ...cbdc.......ffccccccfffffff...
                                                ...fbdc....fffcbbbbbbbbbbbbbcff.
                                                ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
                                                ....fcdffcccccbbbcbcbbbffbbbbcbf
                                                ....fcbbccccccbbbcbcbbbff1111bbf
                                                ...fcbbccccccccbbbcbb11111111bf.
                                                ...fbbfffcccccccbbbb11bc33cccf..
                                                ..fbbf..cbdbcccccbbb111c131cf...
                                                ..fff....cbdddddccbbc111c33f....
                                                ..........ccbddccbbdf1111ff.....
                                                ............ccfbbbdfccccc.......
                                                ..............fffff.............
                        """),
                        img("""
                            ..............fffcc.............
                                                ..............fbbddc............
                                                ...............fbbddc...........
                                                ccc............fcbbccf..........
                                                cbbcc.........ffccccccffffff....
                                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                                ..fccbcccccccccbbbbbb11111111bf.
                                                .fcbbfffccccccccbbbb11cc33cccf..
                                                .fbbf...cbdbcccccbbb111c131cf...
                                                fbbf.....ccdddddfbbbc111c33f....
                                                fff........ccddfbbdbf1111ff.....
                                                .............cfbbdbfccccc.......
                                                ..............fffff.............
                        """)],
                    150,
                    True)
game.on_update_interval(2000, on_update_interval)

def on_update_interval2():
    global projectile
    if Difficulty == 1:
        projectile = sprites.create_projectile_from_side(img("""
                ..............fffcc.............
                            ..............fcbddcc...........
                            ...............fbbddcc..........
                            ...............fcbbccf..........
                            ..ccc.........ffccccccfffff.....
                            ..cbbcc....fffcbbbbcbbbbbbbff...
                            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                            ...fbbdcfcccccbbbcbcbbffbbbbbbff
                            ....fbbffcccccbbbbbcb1ff11bbbcbf
                            ....fcbbcccccccbbbbb11111111bbbf
                            ....fcccccccccccbbbb11cc33111bf.
                            ...fcbbffbdbcccccbbb111c13cccf..
                            ...fbbf..ccddddcfbbbc111c31cf...
                            ..fbbf.....ccdccbbdbf111cccf....
                            ..fff........ccbbdcfcccc........
                            ..............fffff.............
            """),
            info.score() * randint(1, 10),
            0)
        projectile.set_position(0, randint(0, 160))
        animation.run_image_animation(projectile,
            [img("""
                    ..............fffcc.............
                                ..............fcbddcc...........
                                ...............fbbddcc..........
                                ...............fcbbccf..........
                                ..ccc.........ffccccccfffff.....
                                ..cbbcc....fffcbbbbcbbbbbbbff...
                                ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                                ...fbbdcfcccccbbbcbcbbffbbbbbbff
                                ....fbbffcccccbbbbbcb1ff11bbbcbf
                                ....fcbbcccccccbbbbb11111111bbbf
                                ....fcccccccccccbbbb11cc33111bf.
                                ...fcbbffbdbcccccbbb111c13cccf..
                                ...fbbf..ccddddcfbbbc111c31cf...
                                ..fbbf.....ccdccbbdbf111cccf....
                                ..fff........ccbbdcfcccc........
                                ..............fffff.............
                """),
                img("""
                    ..............fffcc.............
                                ..............fbbddc............
                                ...............fbbddc...........
                                ccc............fcbbccf..........
                                cbbcc.........ffccccccffffff....
                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                ..fccbcccccccccbbbbbb11111111bf.
                                .fcbbfffccccccccbbbb11cc33cccf..
                                .fbbf...cbdbcccccbbb111c131cf...
                                fbbf.....ccdddddfbbbc111c33f....
                                fff........ccddfbbdbf1111ff.....
                                .............cfbbdbfccccc.......
                                ..............fffff.............
                """),
                img("""
                    ..............fffc..............
                                ..............fbddcc............
                                ..ccc.........ffbddbc...........
                                ..cbbc.........fcbbccf..........
                                ...cbdc.......ffccccccfffffff...
                                ...fbdc....fffcbbbbbbbbbbbbbcff.
                                ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
                                ....fcdffcccccbbbcbcbbbffbbbbcbf
                                ....fcbbccccccbbbcbcbbbff1111bbf
                                ...fcbbccccccccbbbcbb11111111bf.
                                ...fbbfffcccccccbbbb11bc33cccf..
                                ..fbbf..cbdbcccccbbb111c131cf...
                                ..fff....cbdddddccbbc111c33f....
                                ..........ccbddccbbdf1111ff.....
                                ............ccfbbbdfccccc.......
                                ..............fffff.............
                """),
                img("""
                    ..............fffcc.............
                                ..............fbbddc............
                                ...............fbbddc...........
                                ccc............fcbbccf..........
                                cbbcc.........ffccccccffffff....
                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                ..fccbcccccccccbbbbbb11111111bf.
                                .fcbbfffccccccccbbbb11cc33cccf..
                                .fbbf...cbdbcccccbbb111c131cf...
                                fbbf.....ccdddddfbbbc111c33f....
                                fff........ccddfbbdbf1111ff.....
                                .............cfbbdbfccccc.......
                                ..............fffff.............
                """)],
            150,
            True)
        projectile = sprites.create_projectile_from_side(img("""
                ..............fffcc.............
                            ..............fcbddcc...........
                            ...............fbbddcc..........
                            ...............fcbbccf..........
                            ..ccc.........ffccccccfffff.....
                            ..cbbcc....fffcbbbbcbbbbbbbff...
                            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                            ...fbbdcfcccccbbbcbcbbffbbbbbbff
                            ....fbbffcccccbbbbbcb1ff11bbbcbf
                            ....fcbbcccccccbbbbb11111111bbbf
                            ....fcccccccccccbbbb11cc33111bf.
                            ...fcbbffbdbcccccbbb111c13cccf..
                            ...fbbf..ccddddcfbbbc111c31cf...
                            ..fbbf.....ccdccbbdbf111cccf....
                            ..fff........ccbbdcfcccc........
                            ..............fffff.............
            """),
            info.score() * randint(1, 10),
            0)
        projectile.set_position(0, randint(0, 160))
        animation.run_image_animation(projectile,
            [img("""
                    ..............fffcc.............
                                ..............fcbddcc...........
                                ...............fbbddcc..........
                                ...............fcbbccf..........
                                ..ccc.........ffccccccfffff.....
                                ..cbbcc....fffcbbbbcbbbbbbbff...
                                ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                                ...fbbdcfcccccbbbcbcbbffbbbbbbff
                                ....fbbffcccccbbbbbcb1ff11bbbcbf
                                ....fcbbcccccccbbbbb11111111bbbf
                                ....fcccccccccccbbbb11cc33111bf.
                                ...fcbbffbdbcccccbbb111c13cccf..
                                ...fbbf..ccddddcfbbbc111c31cf...
                                ..fbbf.....ccdccbbdbf111cccf....
                                ..fff........ccbbdcfcccc........
                                ..............fffff.............
                """),
                img("""
                    ..............fffcc.............
                                ..............fbbddc............
                                ...............fbbddc...........
                                ccc............fcbbccf..........
                                cbbcc.........ffccccccffffff....
                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                ..fccbcccccccccbbbbbb11111111bf.
                                .fcbbfffccccccccbbbb11cc33cccf..
                                .fbbf...cbdbcccccbbb111c131cf...
                                fbbf.....ccdddddfbbbc111c33f....
                                fff........ccddfbbdbf1111ff.....
                                .............cfbbdbfccccc.......
                                ..............fffff.............
                """),
                img("""
                    ..............fffc..............
                                ..............fbddcc............
                                ..ccc.........ffbddbc...........
                                ..cbbc.........fcbbccf..........
                                ...cbdc.......ffccccccfffffff...
                                ...fbdc....fffcbbbbbbbbbbbbbcff.
                                ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
                                ....fcdffcccccbbbcbcbbbffbbbbcbf
                                ....fcbbccccccbbbcbcbbbff1111bbf
                                ...fcbbccccccccbbbcbb11111111bf.
                                ...fbbfffcccccccbbbb11bc33cccf..
                                ..fbbf..cbdbcccccbbb111c131cf...
                                ..fff....cbdddddccbbc111c33f....
                                ..........ccbddccbbdf1111ff.....
                                ............ccfbbbdfccccc.......
                                ..............fffff.............
                """),
                img("""
                    ..............fffcc.............
                                ..............fbbddc............
                                ...............fbbddc...........
                                ccc............fcbbccf..........
                                cbbcc.........ffccccccffffff....
                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                ..fccbcccccccccbbbbbb11111111bf.
                                .fcbbfffccccccccbbbb11cc33cccf..
                                .fbbf...cbdbcccccbbb111c131cf...
                                fbbf.....ccdddddfbbbc111c33f....
                                fff........ccddfbbdbf1111ff.....
                                .............cfbbdbfccccc.......
                                ..............fffff.............
                """)],
            150,
            True)
        projectile = sprites.create_projectile_from_side(img("""
                ..............fffcc.............
                            ..............fcbddcc...........
                            ...............fbbddcc..........
                            ...............fcbbccf..........
                            ..ccc.........ffccccccfffff.....
                            ..cbbcc....fffcbbbbcbbbbbbbff...
                            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                            ...fbbdcfcccccbbbcbcbbffbbbbbbff
                            ....fbbffcccccbbbbbcb1ff11bbbcbf
                            ....fcbbcccccccbbbbb11111111bbbf
                            ....fcccccccccccbbbb11cc33111bf.
                            ...fcbbffbdbcccccbbb111c13cccf..
                            ...fbbf..ccddddcfbbbc111c31cf...
                            ..fbbf.....ccdccbbdbf111cccf....
                            ..fff........ccbbdcfcccc........
                            ..............fffff.............
            """),
            info.score() * randint(1, 10),
            0)
        projectile.set_position(0, randint(0, 160))
        animation.run_image_animation(projectile,
            [img("""
                    ..............fffcc.............
                                ..............fcbddcc...........
                                ...............fbbddcc..........
                                ...............fcbbccf..........
                                ..ccc.........ffccccccfffff.....
                                ..cbbcc....fffcbbbbcbbbbbbbff...
                                ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                                ...fbbdcfcccccbbbcbcbbffbbbbbbff
                                ....fbbffcccccbbbbbcb1ff11bbbcbf
                                ....fcbbcccccccbbbbb11111111bbbf
                                ....fcccccccccccbbbb11cc33111bf.
                                ...fcbbffbdbcccccbbb111c13cccf..
                                ...fbbf..ccddddcfbbbc111c31cf...
                                ..fbbf.....ccdccbbdbf111cccf....
                                ..fff........ccbbdcfcccc........
                                ..............fffff.............
                """),
                img("""
                    ..............fffcc.............
                                ..............fbbddc............
                                ...............fbbddc...........
                                ccc............fcbbccf..........
                                cbbcc.........ffccccccffffff....
                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                ..fccbcccccccccbbbbbb11111111bf.
                                .fcbbfffccccccccbbbb11cc33cccf..
                                .fbbf...cbdbcccccbbb111c131cf...
                                fbbf.....ccdddddfbbbc111c33f....
                                fff........ccddfbbdbf1111ff.....
                                .............cfbbdbfccccc.......
                                ..............fffff.............
                """),
                img("""
                    ..............fffc..............
                                ..............fbddcc............
                                ..ccc.........ffbddbc...........
                                ..cbbc.........fcbbccf..........
                                ...cbdc.......ffccccccfffffff...
                                ...fbdc....fffcbbbbbbbbbbbbbcff.
                                ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
                                ....fcdffcccccbbbcbcbbbffbbbbcbf
                                ....fcbbccccccbbbcbcbbbff1111bbf
                                ...fcbbccccccccbbbcbb11111111bf.
                                ...fbbfffcccccccbbbb11bc33cccf..
                                ..fbbf..cbdbcccccbbb111c131cf...
                                ..fff....cbdddddccbbc111c33f....
                                ..........ccbddccbbdf1111ff.....
                                ............ccfbbbdfccccc.......
                                ..............fffff.............
                """),
                img("""
                    ..............fffcc.............
                                ..............fbbddc............
                                ...............fbbddc...........
                                ccc............fcbbccf..........
                                cbbcc.........ffccccccffffff....
                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                ..fccbcccccccccbbbbbb11111111bf.
                                .fcbbfffccccccccbbbb11cc33cccf..
                                .fbbf...cbdbcccccbbb111c131cf...
                                fbbf.....ccdddddfbbbc111c33f....
                                fff........ccddfbbdbf1111ff.....
                                .............cfbbdbfccccc.......
                                ..............fffff.............
                """)],
            150,
            True)
        projectile = sprites.create_projectile_from_side(img("""
                ..............fffcc.............
                            ..............fcbddcc...........
                            ...............fbbddcc..........
                            ...............fcbbccf..........
                            ..ccc.........ffccccccfffff.....
                            ..cbbcc....fffcbbbbcbbbbbbbff...
                            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                            ...fbbdcfcccccbbbcbcbbffbbbbbbff
                            ....fbbffcccccbbbbbcb1ff11bbbcbf
                            ....fcbbcccccccbbbbb11111111bbbf
                            ....fcccccccccccbbbb11cc33111bf.
                            ...fcbbffbdbcccccbbb111c13cccf..
                            ...fbbf..ccddddcfbbbc111c31cf...
                            ..fbbf.....ccdccbbdbf111cccf....
                            ..fff........ccbbdcfcccc........
                            ..............fffff.............
            """),
            info.score() * randint(1, 10),
            0)
        projectile.set_position(0, randint(0, 160))
        animation.run_image_animation(projectile,
            [img("""
                    ..............fffcc.............
                                ..............fcbddcc...........
                                ...............fbbddcc..........
                                ...............fcbbccf..........
                                ..ccc.........ffccccccfffff.....
                                ..cbbcc....fffcbbbbcbbbbbbbff...
                                ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                                ...fbbdcfcccccbbbcbcbbffbbbbbbff
                                ....fbbffcccccbbbbbcb1ff11bbbcbf
                                ....fcbbcccccccbbbbb11111111bbbf
                                ....fcccccccccccbbbb11cc33111bf.
                                ...fcbbffbdbcccccbbb111c13cccf..
                                ...fbbf..ccddddcfbbbc111c31cf...
                                ..fbbf.....ccdccbbdbf111cccf....
                                ..fff........ccbbdcfcccc........
                                ..............fffff.............
                """),
                img("""
                    ..............fffcc.............
                                ..............fbbddc............
                                ...............fbbddc...........
                                ccc............fcbbccf..........
                                cbbcc.........ffccccccffffff....
                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                ..fccbcccccccccbbbbbb11111111bf.
                                .fcbbfffccccccccbbbb11cc33cccf..
                                .fbbf...cbdbcccccbbb111c131cf...
                                fbbf.....ccdddddfbbbc111c33f....
                                fff........ccddfbbdbf1111ff.....
                                .............cfbbdbfccccc.......
                                ..............fffff.............
                """),
                img("""
                    ..............fffc..............
                                ..............fbddcc............
                                ..ccc.........ffbddbc...........
                                ..cbbc.........fcbbccf..........
                                ...cbdc.......ffccccccfffffff...
                                ...fbdc....fffcbbbbbbbbbbbbbcff.
                                ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
                                ....fcdffcccccbbbcbcbbbffbbbbcbf
                                ....fcbbccccccbbbcbcbbbff1111bbf
                                ...fcbbccccccccbbbcbb11111111bf.
                                ...fbbfffcccccccbbbb11bc33cccf..
                                ..fbbf..cbdbcccccbbb111c131cf...
                                ..fff....cbdddddccbbc111c33f....
                                ..........ccbddccbbdf1111ff.....
                                ............ccfbbbdfccccc.......
                                ..............fffff.............
                """),
                img("""
                    ..............fffcc.............
                                ..............fbbddc............
                                ...............fbbddc...........
                                ccc............fcbbccf..........
                                cbbcc.........ffccccccffffff....
                                .cbbdc.....fffcbbbbbbbbbbbbbff..
                                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                                ..fccbcccccccccbbbbbb11111111bf.
                                .fcbbfffccccccccbbbb11cc33cccf..
                                .fbbf...cbdbcccccbbb111c131cf...
                                fbbf.....ccdddddfbbbc111c33f....
                                fff........ccddfbbdbf1111ff.....
                                .............cfbbdbfccccc.......
                                ..............fffff.............
                """)],
            150,
            True)
game.on_update_interval(2000, on_update_interval2)

def on_forever():
    if info.score() == 5:
        Bottle_2.set_position(randint(5, 160), 0)
        Bottle_2.set_velocity(0, randint(50, 100))
    if info.score() == 6:
        Bottle_3.set_position(randint(5, 160), 0)
        Bottle_3.set_velocity(0, randint(50, 100))
    if info.score() == 7:
        Bottle_4.set_position(randint(5, 160), 0)
        Bottle_4.set_velocity(0, randint(50, 100))
    if info.score() == 8:
        Bottle_5.set_position(randint(5, 160), 0)
        Bottle_5.set_velocity(0, randint(50, 100))
    if Fish.x < -1:
        game.game_over(False)
        game.set_game_over_scoring_type(game.ScoringType.HIGH_SCORE)
        if randint(0, 10) == 1:
            game.show_long_text("Plastic production has skyrocketed from 2.3 million tons in 1950 to 448 million tons in 2015",
                DialogLayout.FULL)
        elif randint(0, 10) == 2:
            game.show_long_text("Ocean acidification, caused by carbon dioxide dissolving into seawater from burning off fossil fuels, continues to lower the pH level of the water.",
                DialogLayout.FULL)
        elif randint(0, 10) == 3:
            game.show_long_text("3", DialogLayout.FULL)
        elif randint(0, 10) == 4:
            game.show_long_text("4", DialogLayout.FULL)
        elif randint(0, 10) == 5:
            game.show_long_text("5", DialogLayout.FULL)
        elif randint(0, 10) == 6:
            game.show_long_text("6", DialogLayout.FULL)
        elif randint(0, 10) == 7:
            game.show_long_text("7", DialogLayout.FULL)
        elif randint(0, 10) == 8:
            game.show_long_text("8", DialogLayout.FULL)
        elif randint(0, 10) == 9:
            game.show_long_text("9", DialogLayout.FULL)
        elif randint(0, 10) == 10:
            game.show_long_text("10", DialogLayout.FULL)
        else:
            game.show_long_text("Hi, who ever is looking at the code, it's currently 3:30am",
                DialogLayout.FULL)
    if Fish.x > 160:
        game.game_over(False)
        game.set_game_over_scoring_type(game.ScoringType.HIGH_SCORE)
        if randint(0, 10) == 1:
            game.show_long_text("1", DialogLayout.FULL)
        elif randint(0, 10) == 2:
            game.show_long_text("2", DialogLayout.FULL)
        elif randint(0, 10) == 3:
            game.show_long_text("3", DialogLayout.FULL)
        elif randint(0, 10) == 4:
            game.show_long_text("4", DialogLayout.FULL)
        elif randint(0, 10) == 5:
            game.show_long_text("5", DialogLayout.FULL)
        elif randint(0, 10) == 6:
            game.show_long_text("6", DialogLayout.FULL)
        elif randint(0, 10) == 7:
            game.show_long_text("7", DialogLayout.FULL)
        elif randint(0, 10) == 8:
            game.show_long_text("8", DialogLayout.FULL)
        elif randint(0, 10) == 9:
            game.show_long_text("9", DialogLayout.FULL)
        elif randint(0, 10) == 10:
            game.show_long_text("10", DialogLayout.FULL)
        else:
            game.show_long_text("Hi, who ever is looking at the code, it's currently 3:30am",
                DialogLayout.FULL)
    if Fish.y > 120:
        game.game_over(False)
        game.set_game_over_scoring_type(game.ScoringType.HIGH_SCORE)
        if randint(0, 10) == 1:
            game.show_long_text("1", DialogLayout.FULL)
        elif randint(0, 10) == 2:
            game.show_long_text("2", DialogLayout.FULL)
        elif randint(0, 10) == 3:
            game.show_long_text("3", DialogLayout.FULL)
        elif randint(0, 10) == 4:
            game.show_long_text("4", DialogLayout.FULL)
        elif randint(0, 10) == 5:
            game.show_long_text("5", DialogLayout.FULL)
        elif randint(0, 10) == 6:
            game.show_long_text("6", DialogLayout.FULL)
        elif randint(0, 10) == 7:
            game.show_long_text("7", DialogLayout.FULL)
        elif randint(0, 10) == 8:
            game.show_long_text("8", DialogLayout.FULL)
        elif randint(0, 10) == 9:
            game.show_long_text("9", DialogLayout.FULL)
        elif randint(0, 10) == 10:
            game.show_long_text("10", DialogLayout.FULL)
        else:
            game.show_long_text("Hi, who ever is looking at the code, it's currently 3:30am",
                DialogLayout.FULL)
    if Fish.y < -1:
        game.game_over(False)
        game.set_game_over_scoring_type(game.ScoringType.HIGH_SCORE)
        if randint(0, 10) == 1:
            game.show_long_text("1", DialogLayout.FULL)
        elif randint(0, 10) == 2:
            game.show_long_text("2", DialogLayout.FULL)
        elif randint(0, 10) == 3:
            game.show_long_text("3", DialogLayout.FULL)
        elif randint(0, 10) == 4:
            game.show_long_text("4", DialogLayout.FULL)
        elif randint(0, 10) == 5:
            game.show_long_text("5", DialogLayout.FULL)
        elif randint(0, 10) == 6:
            game.show_long_text("6", DialogLayout.FULL)
        elif randint(0, 10) == 7:
            game.show_long_text("7", DialogLayout.FULL)
        elif randint(0, 10) == 8:
            game.show_long_text("8", DialogLayout.FULL)
        elif randint(0, 10) == 9:
            game.show_long_text("9", DialogLayout.FULL)
        elif randint(0, 10) == 10:
            game.show_long_text("10", DialogLayout.FULL)
        else:
            game.show_long_text("Hi, who ever is looking at the code, it's currently 3:30am",
                DialogLayout.FULL)
forever(on_forever)

def on_update_interval3():
    if Difficulty == 0:
        if Bottle_1.y > 120:
            Bottle_1.set_position(randint(0, 160), 0)
            Bottle_1.set_velocity(0, 100)
            info.change_score_by(1)
        if info.score() >= 5:
            if Bottle_2.y > 120:
                Bottle_2.set_position(randint(0, 160), 0)
                Bottle_2.set_velocity(0, info.score() * randint(10, 100))
                info.change_score_by(1)
            if Bottle_3.y > 120:
                Bottle_3.set_position(randint(0, 160), 0)
                Bottle_3.set_velocity(0, info.score() * randint(10, 100))
                info.change_score_by(1)
            if Bottle_4.y > 120:
                Bottle_4.set_position(randint(0, 160), 0)
                Bottle_4.set_velocity(0, info.score() * randint(10, 100))
                info.change_score_by(1)
            if Bottle_5.y > 120:
                Bottle_5.set_position(randint(0, 160), 0)
                Bottle_5.set_velocity(0, info.score() * randint(10, 100))
                info.change_score_by(1)
game.on_update_interval(500, on_update_interval3)

def on_update_interval4():
    if Difficulty == 1:
        if Bottle_1.y >= 119:
            Bottle_1.set_position(randint(0, 160), 0)
            Bottle_1.set_velocity(randint(20, 100), 100)
            info.change_score_by(1)
        if info.score() >= 5:
            if Bottle_2.y >= 119:
                Bottle_2.set_position(randint(0, 160), 0)
                Bottle_2.set_velocity(randint(20, 100), 100)
                info.change_score_by(1)
            if Bottle_3.y >= 119:
                Bottle_3.set_position(randint(0, 160), 0)
                Bottle_3.set_velocity(randint(20, 100), 100)
                info.change_score_by(1)
            if Bottle_4.y >= 119:
                Bottle_4.set_position(randint(0, 160), 0)
                Bottle_4.set_velocity(randint(20, 100), 100)
                info.change_score_by(1)
            if Bottle_5.y >= 119:
                Bottle_5.set_position(randint(0, 160), 0)
                Bottle_5.set_velocity(randint(20, 100), 100)
                info.change_score_by(1)
game.on_update_interval(500, on_update_interval4)
