namespace SpriteKind {
    export const Boss = SpriteKind.create()
}
controller.combos.attachCombo("B+A", function () {
    Difficulty = 1
    music.play(music.melodyPlayable(music.baDing), music.PlaybackMode.UntilDone)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite2, otherSprite2) {
    game.gameOver(false)
    game.setGameOverScoringType(game.ScoringType.HighScore)
    if (randint(0, 10) == 1) {
        game.showLongText("It's estimated seafood lovers eat 11,000 pieces of toxic plastic every year.", DialogLayout.Full)
    } else if (randint(0, 10) == 2) {
        game.showLongText("1 in 3 fish for human consumption contains plastic.", DialogLayout.Full)
    } else if (randint(0, 10) == 3) {
        game.showLongText("Microplastic can be found in tap water and salt.", DialogLayout.Full)
    } else if (randint(0, 10) == 4) {
        game.showLongText("Numerous chemicals used to produce plastic are known to be carcinogenic and to interfere with the body's hormone system causing reproductive, neurological, and immune disorders in both humans and wildlife.", DialogLayout.Full)
    } else if (randint(0, 10) == 5) {
        game.showLongText("Excessive marine pollution has helped create 500 dead zones (the size of the United Kingdom's surface (245,000 km²) in the ocean – this number will double every decade.", DialogLayout.Full)
    } else if (randint(0, 10) == 6) {
        game.showLongText("70% of Earth's oxygen is produced by marine plants AND 30% of our CO2 emissions are absorbed by the oceans.", DialogLayout.Full)
    } else if (randint(0, 10) == 7) {
        game.showLongText("18 billion pounds of plastic pollution flows into the sea from coastal regions yearly.", DialogLayout.Full)
    } else if (randint(0, 10) == 8) {
        game.showLongText("Only 10 river systems contribute to 90% of the plastic that flows into the sea.", DialogLayout.Full)
    } else if (randint(0, 10) == 9) {
        game.showLongText("500 billion plastic bottles are used every year – Meaning there are 66 times as many bottles as there are humans on the planet.", DialogLayout.Full)
    } else if (randint(0, 10) == 10) {
        game.showLongText("A plastic bottle can last for 450 years in the marine environment.", DialogLayout.Full)
    } else {
        game.showLongText("Hi, who ever is looking at the code, it's currently 3:30am", DialogLayout.Full)
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    game.gameOver(false)
    game.setGameOverScoringType(game.ScoringType.HighScore)
    if (randint(0, 10) == 1) {
        game.showLongText("14% of all litter is from drinks containers.", DialogLayout.Full)
    } else if (randint(0, 10) == 2) {
        game.showLongText("Less than half of the bottles bought in 2016 were recycled.", DialogLayout.Full)
    } else if (randint(0, 10) == 3) {
        game.showLongText("Scientists estimate 7.5 million straws pollute US coastlines & between 437 million to 8.3 billion plastic straws on coastlines around the world.", DialogLayout.Full)
    } else if (randint(0, 10) == 4) {
        game.showLongText("Up to one trillion plastic bags are used worldwide each year – that's 160,000 a second.", DialogLayout.Full)
    } else if (randint(0, 10) == 5) {
        game.showLongText("It can take anything between 20-1000 years for a plastic bag to break up.", DialogLayout.Full)
    } else if (randint(0, 10) == 6) {
        game.showLongText("Plastics consistently make up 60 to 90% of all marine debris studied.", DialogLayout.Full)
    } else if (randint(0, 10) == 7) {
        game.showLongText("20% of all plastic waste in the sea comes from marine sources such as nets, ropes, and lines.", DialogLayout.Full)
    } else if (randint(0, 10) == 8) {
        game.showLongText("60% of the materials that form clothing are forms of plastic (Nylon, acrylic, polyester, etc). Your typical clothes wash will produce around 700,000 microplastic fibers.", DialogLayout.Full)
    } else if (randint(0, 10) == 9) {
        game.showLongText("Marine plastic pollution has affected 100% of marine turtles, 59% of whales, 36% of seals and 40% of seabirds of those examined.", DialogLayout.Full)
    } else if (randint(0, 10) == 10) {
        game.showLongText("Over 1 million seabirds and 100,000 marine mammals are killed by ocean plastic every year.", DialogLayout.Full)
    } else {
        game.showLongText("Hi, who ever is looking at the code, it's currently 3:30am", DialogLayout.Full)
    }
})
controller.combos.attachCombo("up, up, down, down, left, right, left, right, B, A", function () {
    Difficulty = 2
    music.play(music.melodyPlayable(music.siren), music.PlaybackMode.UntilDone)
})
let projectile: Sprite = null
let Difficulty = 0
game.setDialogTextColor(15)
game.showLongText("Every day ~8 million pieces of trash make its way into our oceans. This number is set to double by 2034. Let's see how life is like for a fish in the modern day ocean. Use WASD or the arrow keys or move and avoid getting caught in garbage or by a predator.", DialogLayout.Full)
info.setScore(0)
scene.setBackgroundImage(assets.image`myImage`)
let Fish = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . c c c c . . . . 
    . . . . . . c c d d d d c . . . 
    . . . . . c c c c c c d c . . . 
    . . . . c c 4 4 4 4 d c c . . . 
    . . . c 4 d 4 4 4 4 4 1 c . c c 
    . . c 4 4 4 1 4 4 4 4 d 1 c 4 c 
    . c 4 4 4 4 1 4 4 4 4 4 1 c 4 c 
    f 4 4 4 4 4 1 4 4 4 4 4 1 4 4 f 
    f 4 4 4 f 4 1 c c 4 4 4 1 f 4 f 
    f 4 4 4 4 4 1 4 4 f 4 4 d f 4 f 
    . f 4 4 4 4 1 c 4 f 4 d f f f f 
    . . f f 4 d 4 4 f f 4 c f c . . 
    . . . . f f 4 4 4 4 c d b c . . 
    . . . . . . f f f f d d d c . . 
    . . . . . . . . . . c c c . . . 
    `, SpriteKind.Player)
controller.moveSprite(Fish, 100, 100)
let Bottle_1 = sprites.create(assets.image`Bottle 1`, SpriteKind.Enemy)
let Bottle_2 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    .....7977777777.....
    .....7777777777.....
    ......66666666......
    ......99999999......
    .....9999999999.....
    .....9999999999.....
    .....9999999999.....
    .....7777777777.....
    .....7777777777.....
    .....7777777776.....
    .....7777777776.....
    ......76666666......
    ....................
    ....................
    `, SpriteKind.Enemy)
let Bottle_3 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ........4eee........
    .......eeeeee.......
    .........cc.........
    .........4c.........
    ........4444........
    .......444444.......
    ......44444444......
    .....4444444444.....
    .....eeeeeeeeee.....
    .....eeeeeeeecc.....
    ......eeeeeecc......
    .......eccccc.......
    ....................
    ....................
    `, SpriteKind.Enemy)
let Bottle_4 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ........dd55........
    ........5555........
    .........44.........
    ........dddd........
    ........dddd........
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    ........dddd........
    ........4444........
    ....................
    `, SpriteKind.Enemy)
let Bottle_5 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    .........888........
    .........888........
    ......888888888.....
    ........fffff.......
    .......8888888......
    .......8998888......
    .......8988888......
    .......8888888......
    .......8888888......
    .......8888888......
    ......888888888.....
    ......fffffffff.....
    ....................
    ....................
    `, SpriteKind.Enemy)
Bottle_1.setPosition(randint(5, 160), 0)
Bottle_1.setVelocity(0, 100)
Bottle_2.setPosition(0, 0)
Bottle_3.setPosition(0, 0)
Bottle_4.setPosition(0, 0)
Bottle_5.setPosition(0, 0)
animation.runImageAnimation(
Fish,
[img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . c c c c . . . . 
    . . . . . . c c d d d d c . . . 
    . . . . . c c c c c c d c . . . 
    . . . . c c 4 4 4 4 d c c . . . 
    . . . c 4 d 4 4 4 4 4 1 c . c c 
    . . c 4 4 4 1 4 4 4 4 d 1 c 4 c 
    . c 4 4 4 4 1 4 4 4 4 4 1 c 4 c 
    f 4 4 4 4 4 1 4 4 4 4 4 1 4 4 f 
    f 4 4 4 f 4 1 c c 4 4 4 1 f 4 f 
    f 4 4 4 4 4 1 4 4 f 4 4 d f 4 f 
    . f 4 4 4 4 1 c 4 f 4 d f f f f 
    . . f f 4 d 4 4 f f 4 c f c . . 
    . . . . f f 4 4 4 4 c d b c . . 
    . . . . . . f f f f d d d c . . 
    . . . . . . . . . . c c c . . . 
    `,img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . c c c c c . . . . 
    . . . . . . c d d d d d c . . . 
    . . . . . . c c c c c d c . . . 
    . . . . . c 4 4 4 4 d c c . . . 
    . . . . c d 4 4 4 4 4 1 c . . . 
    . . . c 4 4 1 4 4 4 4 4 1 c . . 
    . . c 4 4 4 4 1 4 4 4 4 1 c c c 
    . c 4 4 4 4 4 1 c c 4 4 1 4 4 c 
    . c 4 4 4 4 4 1 4 4 f 4 1 f 4 f 
    f 4 4 4 4 f 4 1 c 4 f 4 d f 4 f 
    f 4 4 4 4 4 4 1 4 f f 4 f f 4 f 
    . f 4 4 4 4 1 4 4 4 4 c b c f f 
    . . f f f d 4 4 4 4 c d d c . . 
    . . . . . f f f f f c c c . . . 
    . . . . . . . . . . . . . . . . 
    `,img`
    . . . . . . . . c c c c . . . . 
    . . . . . . c c d d d d c . . . 
    . . . . . c c c c c c d c . . . 
    . . . . c c 4 4 4 4 d c c . c c 
    . . . c 4 d 4 4 4 4 4 1 c c 4 c 
    . . c 4 4 4 1 4 4 4 4 d 1 c 4 f 
    . c 4 4 4 4 1 4 4 4 4 4 1 4 4 f 
    f 4 4 4 4 4 1 1 c f 4 4 1 f 4 f 
    f 4 4 4 f 4 1 c 4 f 4 4 1 f 4 f 
    f 4 4 4 4 4 1 4 4 f 4 4 d f f f 
    . f 4 4 4 4 1 c c 4 4 d f f . . 
    . . f f 4 d 4 4 4 4 4 c f . . . 
    . . . . f f 4 4 4 4 c d b c . . 
    . . . . . . f f f f d d d c . . 
    . . . . . . . . . . c c c . . . 
    . . . . . . . . . . . . . . . . 
    `,img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . c c c c . . . 
    . . . . . . . c c d d d d c . . 
    . . . . . c c c c c c d d c . . 
    . . . c c c 4 4 4 4 d c c c c c 
    . . c 4 4 1 4 4 4 4 4 1 c c 4 f 
    . c 4 4 4 4 1 4 4 4 4 d 1 f 4 f 
    f 4 4 4 4 4 1 4 4 4 4 4 1 f 4 f 
    f 4 4 f 4 4 1 4 c f 4 4 1 4 4 f 
    f 4 4 4 4 4 1 c 4 f 4 4 1 f f f 
    . f 4 4 4 4 1 4 4 f 4 4 d f . . 
    . . f 4 4 1 4 c c 4 4 d f . . . 
    . . . f d 4 4 4 4 4 4 c f . . . 
    . . . . f f 4 4 4 4 c d b c . . 
    . . . . . . f f f f d d d c . . 
    . . . . . . . . . . c c c . . . 
    `],
150,
true
)
game.onUpdateInterval(2000, function () {
    if (Difficulty == 0) {
        if (info.score() >= 10) {
            if (randint(1, 10) <= 5) {
                projectile = sprites.createProjectileFromSide(img`
                    ..............fffcc.............
                    ..............fcbddcc...........
                    ...............fbbddcc..........
                    ...............fcbbccf..........
                    ..ccc.........ffccccccfffff.....
                    ..cbbcc....fffcbbbbcbbbbbbbff...
                    ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                    ...fbbdcfcccccbbbcbcbbffbbbbbbff
                    ....fbbffcccccbbbbbcb1ff11bbbcbf
                    ....fcbbcccccccbbbbb11111111bbbf
                    ....fcccccccccccbbbb11cc33111bf.
                    ...fcbbffbdbcccccbbb111c13cccf..
                    ...fbbf..ccddddcfbbbc111c31cf...
                    ..fbbf.....ccdccbbdbf111cccf....
                    ..fff........ccbbdcfcccc........
                    ..............fffff.............
                    `, randint(10, 100), 0)
                projectile.setPosition(0, randint(0, 160))
                animation.runImageAnimation(
                projectile,
                [img`
                    ..............fffcc.............
                    ..............fcbddcc...........
                    ...............fbbddcc..........
                    ...............fcbbccf..........
                    ..ccc.........ffccccccfffff.....
                    ..cbbcc....fffcbbbbcbbbbbbbff...
                    ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                    ...fbbdcfcccccbbbcbcbbffbbbbbbff
                    ....fbbffcccccbbbbbcb1ff11bbbcbf
                    ....fcbbcccccccbbbbb11111111bbbf
                    ....fcccccccccccbbbb11cc33111bf.
                    ...fcbbffbdbcccccbbb111c13cccf..
                    ...fbbf..ccddddcfbbbc111c31cf...
                    ..fbbf.....ccdccbbdbf111cccf....
                    ..fff........ccbbdcfcccc........
                    ..............fffff.............
                    `,img`
                    ..............fffcc.............
                    ..............fbbddc............
                    ...............fbbddc...........
                    ccc............fcbbccf..........
                    cbbcc.........ffccccccffffff....
                    .cbbdc.....fffcbbbbbbbbbbbbbff..
                    .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                    ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                    ..fcbbbcccccccbbbcbcb1ff1111bbbf
                    ..fccbcccccccccbbbbbb11111111bf.
                    .fcbbfffccccccccbbbb11cc33cccf..
                    .fbbf...cbdbcccccbbb111c131cf...
                    fbbf.....ccdddddfbbbc111c33f....
                    fff........ccddfbbdbf1111ff.....
                    .............cfbbdbfccccc.......
                    ..............fffff.............
                    `,img`
                    ..............fffc..............
                    ..............fbddcc............
                    ..ccc.........ffbddbc...........
                    ..cbbc.........fcbbccf..........
                    ...cbdc.......ffccccccfffffff...
                    ...fbdc....fffcbbbbbbbbbbbbbcff.
                    ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
                    ....fcdffcccccbbbcbcbbbffbbbbcbf
                    ....fcbbccccccbbbcbcbbbff1111bbf
                    ...fcbbccccccccbbbcbb11111111bf.
                    ...fbbfffcccccccbbbb11bc33cccf..
                    ..fbbf..cbdbcccccbbb111c131cf...
                    ..fff....cbdddddccbbc111c33f....
                    ..........ccbddccbbdf1111ff.....
                    ............ccfbbbdfccccc.......
                    ..............fffff.............
                    `,img`
                    ..............fffcc.............
                    ..............fbbddc............
                    ...............fbbddc...........
                    ccc............fcbbccf..........
                    cbbcc.........ffccccccffffff....
                    .cbbdc.....fffcbbbbbbbbbbbbbff..
                    .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                    ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                    ..fcbbbcccccccbbbcbcb1ff1111bbbf
                    ..fccbcccccccccbbbbbb11111111bf.
                    .fcbbfffccccccccbbbb11cc33cccf..
                    .fbbf...cbdbcccccbbb111c131cf...
                    fbbf.....ccdddddfbbbc111c33f....
                    fff........ccddfbbdbf1111ff.....
                    .............cfbbdbfccccc.......
                    ..............fffff.............
                    `],
                150,
                true
                )
            }
        }
        if (info.score() >= 15) {
            if (randint(1, 10) <= 4) {
                projectile = sprites.createProjectileFromSide(img`
                    ..............fffcc.............
                    ..............fcbddcc...........
                    ...............fbbddcc..........
                    ...............fcbbccf..........
                    ..ccc.........ffccccccfffff.....
                    ..cbbcc....fffcbbbbcbbbbbbbff...
                    ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                    ...fbbdcfcccccbbbcbcbbffbbbbbbff
                    ....fbbffcccccbbbbbcb1ff11bbbcbf
                    ....fcbbcccccccbbbbb11111111bbbf
                    ....fcccccccccccbbbb11cc33111bf.
                    ...fcbbffbdbcccccbbb111c13cccf..
                    ...fbbf..ccddddcfbbbc111c31cf...
                    ..fbbf.....ccdccbbdbf111cccf....
                    ..fff........ccbbdcfcccc........
                    ..............fffff.............
                    `, randint(10, 100), 0)
                projectile.setPosition(0, randint(0, 160))
                animation.runImageAnimation(
                projectile,
                [img`
                    ..............fffcc.............
                    ..............fcbddcc...........
                    ...............fbbddcc..........
                    ...............fcbbccf..........
                    ..ccc.........ffccccccfffff.....
                    ..cbbcc....fffcbbbbcbbbbbbbff...
                    ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                    ...fbbdcfcccccbbbcbcbbffbbbbbbff
                    ....fbbffcccccbbbbbcb1ff11bbbcbf
                    ....fcbbcccccccbbbbb11111111bbbf
                    ....fcccccccccccbbbb11cc33111bf.
                    ...fcbbffbdbcccccbbb111c13cccf..
                    ...fbbf..ccddddcfbbbc111c31cf...
                    ..fbbf.....ccdccbbdbf111cccf....
                    ..fff........ccbbdcfcccc........
                    ..............fffff.............
                    `,img`
                    ..............fffcc.............
                    ..............fbbddc............
                    ...............fbbddc...........
                    ccc............fcbbccf..........
                    cbbcc.........ffccccccffffff....
                    .cbbdc.....fffcbbbbbbbbbbbbbff..
                    .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                    ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                    ..fcbbbcccccccbbbcbcb1ff1111bbbf
                    ..fccbcccccccccbbbbbb11111111bf.
                    .fcbbfffccccccccbbbb11cc33cccf..
                    .fbbf...cbdbcccccbbb111c131cf...
                    fbbf.....ccdddddfbbbc111c33f....
                    fff........ccddfbbdbf1111ff.....
                    .............cfbbdbfccccc.......
                    ..............fffff.............
                    `,img`
                    ..............fffc..............
                    ..............fbddcc............
                    ..ccc.........ffbddbc...........
                    ..cbbc.........fcbbccf..........
                    ...cbdc.......ffccccccfffffff...
                    ...fbdc....fffcbbbbbbbbbbbbbcff.
                    ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
                    ....fcdffcccccbbbcbcbbbffbbbbcbf
                    ....fcbbccccccbbbcbcbbbff1111bbf
                    ...fcbbccccccccbbbcbb11111111bf.
                    ...fbbfffcccccccbbbb11bc33cccf..
                    ..fbbf..cbdbcccccbbb111c131cf...
                    ..fff....cbdddddccbbc111c33f....
                    ..........ccbddccbbdf1111ff.....
                    ............ccfbbbdfccccc.......
                    ..............fffff.............
                    `,img`
                    ..............fffcc.............
                    ..............fbbddc............
                    ...............fbbddc...........
                    ccc............fcbbccf..........
                    cbbcc.........ffccccccffffff....
                    .cbbdc.....fffcbbbbbbbbbbbbbff..
                    .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                    ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                    ..fcbbbcccccccbbbcbcb1ff1111bbbf
                    ..fccbcccccccccbbbbbb11111111bf.
                    .fcbbfffccccccccbbbb11cc33cccf..
                    .fbbf...cbdbcccccbbb111c131cf...
                    fbbf.....ccdddddfbbbc111c33f....
                    fff........ccddfbbdbf1111ff.....
                    .............cfbbdbfccccc.......
                    ..............fffff.............
                    `],
                150,
                true
                )
            }
        }
        if (info.score() >= 20) {
            if (randint(1, 10) <= 3) {
                projectile = sprites.createProjectileFromSide(img`
                    ..............fffcc.............
                    ..............fcbddcc...........
                    ...............fbbddcc..........
                    ...............fcbbccf..........
                    ..ccc.........ffccccccfffff.....
                    ..cbbcc....fffcbbbbcbbbbbbbff...
                    ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                    ...fbbdcfcccccbbbcbcbbffbbbbbbff
                    ....fbbffcccccbbbbbcb1ff11bbbcbf
                    ....fcbbcccccccbbbbb11111111bbbf
                    ....fcccccccccccbbbb11cc33111bf.
                    ...fcbbffbdbcccccbbb111c13cccf..
                    ...fbbf..ccddddcfbbbc111c31cf...
                    ..fbbf.....ccdccbbdbf111cccf....
                    ..fff........ccbbdcfcccc........
                    ..............fffff.............
                    `, randint(10, 100), 0)
                projectile.setPosition(0, randint(0, 160))
                animation.runImageAnimation(
                projectile,
                [img`
                    ..............fffcc.............
                    ..............fcbddcc...........
                    ...............fbbddcc..........
                    ...............fcbbccf..........
                    ..ccc.........ffccccccfffff.....
                    ..cbbcc....fffcbbbbcbbbbbbbff...
                    ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                    ...fbbdcfcccccbbbcbcbbffbbbbbbff
                    ....fbbffcccccbbbbbcb1ff11bbbcbf
                    ....fcbbcccccccbbbbb11111111bbbf
                    ....fcccccccccccbbbb11cc33111bf.
                    ...fcbbffbdbcccccbbb111c13cccf..
                    ...fbbf..ccddddcfbbbc111c31cf...
                    ..fbbf.....ccdccbbdbf111cccf....
                    ..fff........ccbbdcfcccc........
                    ..............fffff.............
                    `,img`
                    ..............fffcc.............
                    ..............fbbddc............
                    ...............fbbddc...........
                    ccc............fcbbccf..........
                    cbbcc.........ffccccccffffff....
                    .cbbdc.....fffcbbbbbbbbbbbbbff..
                    .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                    ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                    ..fcbbbcccccccbbbcbcb1ff1111bbbf
                    ..fccbcccccccccbbbbbb11111111bf.
                    .fcbbfffccccccccbbbb11cc33cccf..
                    .fbbf...cbdbcccccbbb111c131cf...
                    fbbf.....ccdddddfbbbc111c33f....
                    fff........ccddfbbdbf1111ff.....
                    .............cfbbdbfccccc.......
                    ..............fffff.............
                    `,img`
                    ..............fffc..............
                    ..............fbddcc............
                    ..ccc.........ffbddbc...........
                    ..cbbc.........fcbbccf..........
                    ...cbdc.......ffccccccfffffff...
                    ...fbdc....fffcbbbbbbbbbbbbbcff.
                    ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
                    ....fcdffcccccbbbcbcbbbffbbbbcbf
                    ....fcbbccccccbbbcbcbbbff1111bbf
                    ...fcbbccccccccbbbcbb11111111bf.
                    ...fbbfffcccccccbbbb11bc33cccf..
                    ..fbbf..cbdbcccccbbb111c131cf...
                    ..fff....cbdddddccbbc111c33f....
                    ..........ccbddccbbdf1111ff.....
                    ............ccfbbbdfccccc.......
                    ..............fffff.............
                    `,img`
                    ..............fffcc.............
                    ..............fbbddc............
                    ...............fbbddc...........
                    ccc............fcbbccf..........
                    cbbcc.........ffccccccffffff....
                    .cbbdc.....fffcbbbbbbbbbbbbbff..
                    .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                    ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                    ..fcbbbcccccccbbbcbcb1ff1111bbbf
                    ..fccbcccccccccbbbbbb11111111bf.
                    .fcbbfffccccccccbbbb11cc33cccf..
                    .fbbf...cbdbcccccbbb111c131cf...
                    fbbf.....ccdddddfbbbc111c33f....
                    fff........ccddfbbdbf1111ff.....
                    .............cfbbdbfccccc.......
                    ..............fffff.............
                    `],
                150,
                true
                )
            }
        }
        if (info.score() >= 25) {
            if (randint(1, 10) <= 2) {
                projectile = sprites.createProjectileFromSide(img`
                    ..............fffcc.............
                    ..............fcbddcc...........
                    ...............fbbddcc..........
                    ...............fcbbccf..........
                    ..ccc.........ffccccccfffff.....
                    ..cbbcc....fffcbbbbcbbbbbbbff...
                    ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                    ...fbbdcfcccccbbbcbcbbffbbbbbbff
                    ....fbbffcccccbbbbbcb1ff11bbbcbf
                    ....fcbbcccccccbbbbb11111111bbbf
                    ....fcccccccccccbbbb11cc33111bf.
                    ...fcbbffbdbcccccbbb111c13cccf..
                    ...fbbf..ccddddcfbbbc111c31cf...
                    ..fbbf.....ccdccbbdbf111cccf....
                    ..fff........ccbbdcfcccc........
                    ..............fffff.............
                    `, randint(10, 100), 0)
                projectile.setPosition(0, randint(0, 160))
                animation.runImageAnimation(
                projectile,
                [img`
                    ..............fffcc.............
                    ..............fcbddcc...........
                    ...............fbbddcc..........
                    ...............fcbbccf..........
                    ..ccc.........ffccccccfffff.....
                    ..cbbcc....fffcbbbbcbbbbbbbff...
                    ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                    ...fbbdcfcccccbbbcbcbbffbbbbbbff
                    ....fbbffcccccbbbbbcb1ff11bbbcbf
                    ....fcbbcccccccbbbbb11111111bbbf
                    ....fcccccccccccbbbb11cc33111bf.
                    ...fcbbffbdbcccccbbb111c13cccf..
                    ...fbbf..ccddddcfbbbc111c31cf...
                    ..fbbf.....ccdccbbdbf111cccf....
                    ..fff........ccbbdcfcccc........
                    ..............fffff.............
                    `,img`
                    ..............fffcc.............
                    ..............fbbddc............
                    ...............fbbddc...........
                    ccc............fcbbccf..........
                    cbbcc.........ffccccccffffff....
                    .cbbdc.....fffcbbbbbbbbbbbbbff..
                    .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                    ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                    ..fcbbbcccccccbbbcbcb1ff1111bbbf
                    ..fccbcccccccccbbbbbb11111111bf.
                    .fcbbfffccccccccbbbb11cc33cccf..
                    .fbbf...cbdbcccccbbb111c131cf...
                    fbbf.....ccdddddfbbbc111c33f....
                    fff........ccddfbbdbf1111ff.....
                    .............cfbbdbfccccc.......
                    ..............fffff.............
                    `,img`
                    ..............fffc..............
                    ..............fbddcc............
                    ..ccc.........ffbddbc...........
                    ..cbbc.........fcbbccf..........
                    ...cbdc.......ffccccccfffffff...
                    ...fbdc....fffcbbbbbbbbbbbbbcff.
                    ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
                    ....fcdffcccccbbbcbcbbbffbbbbcbf
                    ....fcbbccccccbbbcbcbbbff1111bbf
                    ...fcbbccccccccbbbcbb11111111bf.
                    ...fbbfffcccccccbbbb11bc33cccf..
                    ..fbbf..cbdbcccccbbb111c131cf...
                    ..fff....cbdddddccbbc111c33f....
                    ..........ccbddccbbdf1111ff.....
                    ............ccfbbbdfccccc.......
                    ..............fffff.............
                    `,img`
                    ..............fffcc.............
                    ..............fbbddc............
                    ...............fbbddc...........
                    ccc............fcbbccf..........
                    cbbcc.........ffccccccffffff....
                    .cbbdc.....fffcbbbbbbbbbbbbbff..
                    .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                    ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                    ..fcbbbcccccccbbbcbcb1ff1111bbbf
                    ..fccbcccccccccbbbbbb11111111bf.
                    .fcbbfffccccccccbbbb11cc33cccf..
                    .fbbf...cbdbcccccbbb111c131cf...
                    fbbf.....ccdddddfbbbc111c33f....
                    fff........ccddfbbdbf1111ff.....
                    .............cfbbdbfccccc.......
                    ..............fffff.............
                    `],
                150,
                true
                )
            }
        }
    }
})
game.onUpdateInterval(2000, function () {
    if (Difficulty == 1) {
        projectile = sprites.createProjectileFromSide(img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `, info.score() * randint(1, 10), 0)
        projectile.setPosition(0, randint(0, 160))
        animation.runImageAnimation(
        projectile,
        [img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `,img`
            ..............fffc..............
            ..............fbddcc............
            ..ccc.........ffbddbc...........
            ..cbbc.........fcbbccf..........
            ...cbdc.......ffccccccfffffff...
            ...fbdc....fffcbbbbbbbbbbbbbcff.
            ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
            ....fcdffcccccbbbcbcbbbffbbbbcbf
            ....fcbbccccccbbbcbcbbbff1111bbf
            ...fcbbccccccccbbbcbb11111111bf.
            ...fbbfffcccccccbbbb11bc33cccf..
            ..fbbf..cbdbcccccbbb111c131cf...
            ..fff....cbdddddccbbc111c33f....
            ..........ccbddccbbdf1111ff.....
            ............ccfbbbdfccccc.......
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `],
        150,
        true
        )
        projectile = sprites.createProjectileFromSide(img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `, info.score() * randint(1, 10), 0)
        projectile.setPosition(0, randint(0, 160))
        animation.runImageAnimation(
        projectile,
        [img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `,img`
            ..............fffc..............
            ..............fbddcc............
            ..ccc.........ffbddbc...........
            ..cbbc.........fcbbccf..........
            ...cbdc.......ffccccccfffffff...
            ...fbdc....fffcbbbbbbbbbbbbbcff.
            ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
            ....fcdffcccccbbbcbcbbbffbbbbcbf
            ....fcbbccccccbbbcbcbbbff1111bbf
            ...fcbbccccccccbbbcbb11111111bf.
            ...fbbfffcccccccbbbb11bc33cccf..
            ..fbbf..cbdbcccccbbb111c131cf...
            ..fff....cbdddddccbbc111c33f....
            ..........ccbddccbbdf1111ff.....
            ............ccfbbbdfccccc.......
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `],
        150,
        true
        )
        projectile = sprites.createProjectileFromSide(img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `, info.score() * randint(1, 10), 0)
        projectile.setPosition(0, randint(0, 160))
        animation.runImageAnimation(
        projectile,
        [img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `,img`
            ..............fffc..............
            ..............fbddcc............
            ..ccc.........ffbddbc...........
            ..cbbc.........fcbbccf..........
            ...cbdc.......ffccccccfffffff...
            ...fbdc....fffcbbbbbbbbbbbbbcff.
            ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
            ....fcdffcccccbbbcbcbbbffbbbbcbf
            ....fcbbccccccbbbcbcbbbff1111bbf
            ...fcbbccccccccbbbcbb11111111bf.
            ...fbbfffcccccccbbbb11bc33cccf..
            ..fbbf..cbdbcccccbbb111c131cf...
            ..fff....cbdddddccbbc111c33f....
            ..........ccbddccbbdf1111ff.....
            ............ccfbbbdfccccc.......
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `],
        150,
        true
        )
        projectile = sprites.createProjectileFromSide(img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `, info.score() * randint(1, 10), 0)
        projectile.setPosition(0, randint(0, 160))
        animation.runImageAnimation(
        projectile,
        [img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `,img`
            ..............fffc..............
            ..............fbddcc............
            ..ccc.........ffbddbc...........
            ..cbbc.........fcbbccf..........
            ...cbdc.......ffccccccfffffff...
            ...fbdc....fffcbbbbbbbbbbbbbcff.
            ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
            ....fcdffcccccbbbcbcbbbffbbbbcbf
            ....fcbbccccccbbbcbcbbbff1111bbf
            ...fcbbccccccccbbbcbb11111111bf.
            ...fbbfffcccccccbbbb11bc33cccf..
            ..fbbf..cbdbcccccbbb111c131cf...
            ..fff....cbdddddccbbc111c33f....
            ..........ccbddccbbdf1111ff.....
            ............ccfbbbdfccccc.......
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `],
        150,
        true
        )
    }
})
forever(function () {
    if (info.score() == 5) {
        Bottle_2.setPosition(randint(5, 160), 0)
        Bottle_2.setVelocity(0, randint(50, 100))
    }
    if (info.score() == 6) {
        Bottle_3.setPosition(randint(5, 160), 0)
        Bottle_3.setVelocity(0, randint(50, 100))
    }
    if (info.score() == 7) {
        Bottle_4.setPosition(randint(5, 160), 0)
        Bottle_4.setVelocity(0, randint(50, 100))
    }
    if (info.score() == 8) {
        Bottle_5.setPosition(randint(5, 160), 0)
        Bottle_5.setVelocity(0, randint(50, 100))
    }
    if (Fish.x < -1) {
        game.gameOver(false)
        game.setGameOverScoringType(game.ScoringType.HighScore)
        if (randint(0, 10) == 1) {
            game.showLongText("Plastic production has skyrocketed from 2.3 million tons in 1950 to 448 million tons in 2015", DialogLayout.Full)
        } else if (randint(0, 10) == 2) {
            game.showLongText("Ocean acidification, caused by carbon dioxide dissolving into seawater from burning off fossil fuels, continues to lower the pH level of the water.", DialogLayout.Full)
        } else if (randint(0, 10) == 3) {
            game.showLongText("3", DialogLayout.Full)
        } else if (randint(0, 10) == 4) {
            game.showLongText("4", DialogLayout.Full)
        } else if (randint(0, 10) == 5) {
            game.showLongText("5", DialogLayout.Full)
        } else if (randint(0, 10) == 6) {
            game.showLongText("6", DialogLayout.Full)
        } else if (randint(0, 10) == 7) {
            game.showLongText("7", DialogLayout.Full)
        } else if (randint(0, 10) == 8) {
            game.showLongText("8", DialogLayout.Full)
        } else if (randint(0, 10) == 9) {
            game.showLongText("9", DialogLayout.Full)
        } else if (randint(0, 10) == 10) {
            game.showLongText("10", DialogLayout.Full)
        } else {
            game.showLongText("Hi, who ever is looking at the code, it's currently 3:30am", DialogLayout.Full)
        }
    }
    if (Fish.x > 160) {
        game.gameOver(false)
        game.setGameOverScoringType(game.ScoringType.HighScore)
        if (randint(0, 10) == 1) {
            game.showLongText("1", DialogLayout.Full)
        } else if (randint(0, 10) == 2) {
            game.showLongText("2", DialogLayout.Full)
        } else if (randint(0, 10) == 3) {
            game.showLongText("3", DialogLayout.Full)
        } else if (randint(0, 10) == 4) {
            game.showLongText("4", DialogLayout.Full)
        } else if (randint(0, 10) == 5) {
            game.showLongText("5", DialogLayout.Full)
        } else if (randint(0, 10) == 6) {
            game.showLongText("6", DialogLayout.Full)
        } else if (randint(0, 10) == 7) {
            game.showLongText("7", DialogLayout.Full)
        } else if (randint(0, 10) == 8) {
            game.showLongText("8", DialogLayout.Full)
        } else if (randint(0, 10) == 9) {
            game.showLongText("9", DialogLayout.Full)
        } else if (randint(0, 10) == 10) {
            game.showLongText("10", DialogLayout.Full)
        } else {
            game.showLongText("Hi, who ever is looking at the code, it's currently 3:30am", DialogLayout.Full)
        }
    }
    if (Fish.y > 120) {
        game.gameOver(false)
        game.setGameOverScoringType(game.ScoringType.HighScore)
        if (randint(0, 10) == 1) {
            game.showLongText("1", DialogLayout.Full)
        } else if (randint(0, 10) == 2) {
            game.showLongText("2", DialogLayout.Full)
        } else if (randint(0, 10) == 3) {
            game.showLongText("3", DialogLayout.Full)
        } else if (randint(0, 10) == 4) {
            game.showLongText("4", DialogLayout.Full)
        } else if (randint(0, 10) == 5) {
            game.showLongText("5", DialogLayout.Full)
        } else if (randint(0, 10) == 6) {
            game.showLongText("6", DialogLayout.Full)
        } else if (randint(0, 10) == 7) {
            game.showLongText("7", DialogLayout.Full)
        } else if (randint(0, 10) == 8) {
            game.showLongText("8", DialogLayout.Full)
        } else if (randint(0, 10) == 9) {
            game.showLongText("9", DialogLayout.Full)
        } else if (randint(0, 10) == 10) {
            game.showLongText("10", DialogLayout.Full)
        } else {
            game.showLongText("Hi, who ever is looking at the code, it's currently 3:30am", DialogLayout.Full)
        }
    }
    if (Fish.y < -1) {
        game.gameOver(false)
        game.setGameOverScoringType(game.ScoringType.HighScore)
        if (randint(0, 10) == 1) {
            game.showLongText("1", DialogLayout.Full)
        } else if (randint(0, 10) == 2) {
            game.showLongText("2", DialogLayout.Full)
        } else if (randint(0, 10) == 3) {
            game.showLongText("3", DialogLayout.Full)
        } else if (randint(0, 10) == 4) {
            game.showLongText("4", DialogLayout.Full)
        } else if (randint(0, 10) == 5) {
            game.showLongText("5", DialogLayout.Full)
        } else if (randint(0, 10) == 6) {
            game.showLongText("6", DialogLayout.Full)
        } else if (randint(0, 10) == 7) {
            game.showLongText("7", DialogLayout.Full)
        } else if (randint(0, 10) == 8) {
            game.showLongText("8", DialogLayout.Full)
        } else if (randint(0, 10) == 9) {
            game.showLongText("9", DialogLayout.Full)
        } else if (randint(0, 10) == 10) {
            game.showLongText("10", DialogLayout.Full)
        } else {
            game.showLongText("Hi, who ever is looking at the code, it's currently 3:30am", DialogLayout.Full)
        }
    }
})
game.onUpdateInterval(500, function () {
    if (Difficulty == 0) {
        if (Bottle_1.y > 120) {
            Bottle_1.setPosition(randint(0, 160), 0)
            Bottle_1.setVelocity(0, 100)
            info.changeScoreBy(1)
        }
        if (info.score() >= 5) {
            if (Bottle_2.y > 120) {
                Bottle_2.setPosition(randint(0, 160), 0)
                Bottle_2.setVelocity(0, info.score() * randint(10, 100))
                info.changeScoreBy(1)
            }
            if (Bottle_3.y > 120) {
                Bottle_3.setPosition(randint(0, 160), 0)
                Bottle_3.setVelocity(0, info.score() * randint(10, 100))
                info.changeScoreBy(1)
            }
            if (Bottle_4.y > 120) {
                Bottle_4.setPosition(randint(0, 160), 0)
                Bottle_4.setVelocity(0, info.score() * randint(10, 100))
                info.changeScoreBy(1)
            }
            if (Bottle_5.y > 120) {
                Bottle_5.setPosition(randint(0, 160), 0)
                Bottle_5.setVelocity(0, info.score() * randint(10, 100))
                info.changeScoreBy(1)
            }
        }
    }
})
game.onUpdateInterval(500, function () {
    if (Difficulty == 1) {
        if (Bottle_1.y >= 119) {
            Bottle_1.setPosition(randint(0, 160), 0)
            Bottle_1.setVelocity(randint(20, 100), 100)
            info.changeScoreBy(1)
        }
        if (info.score() >= 5) {
            if (Bottle_2.y >= 119) {
                Bottle_2.setPosition(randint(0, 160), 0)
                Bottle_2.setVelocity(randint(20, 100), 100)
                info.changeScoreBy(1)
            }
            if (Bottle_3.y >= 119) {
                Bottle_3.setPosition(randint(0, 160), 0)
                Bottle_3.setVelocity(randint(20, 100), 100)
                info.changeScoreBy(1)
            }
            if (Bottle_4.y >= 119) {
                Bottle_4.setPosition(randint(0, 160), 0)
                Bottle_4.setVelocity(randint(20, 100), 100)
                info.changeScoreBy(1)
            }
            if (Bottle_5.y >= 119) {
                Bottle_5.setPosition(randint(0, 160), 0)
                Bottle_5.setVelocity(randint(20, 100), 100)
                info.changeScoreBy(1)
            }
        }
    }
})
game.onUpdateInterval(100, function () {
    if (Difficulty == 2) {
        projectile = sprites.createProjectileFromSide(img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `, info.score() * 100, randint(0, 160))
        projectile.setPosition(0, randint(0, 160))
        animation.runImageAnimation(
        projectile,
        [img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `,img`
            ..............fffc..............
            ..............fbddcc............
            ..ccc.........ffbddbc...........
            ..cbbc.........fcbbccf..........
            ...cbdc.......ffccccccfffffff...
            ...fbdc....fffcbbbbbbbbbbbbbcff.
            ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
            ....fcdffcccccbbbcbcbbbffbbbbcbf
            ....fcbbccccccbbbcbcbbbff1111bbf
            ...fcbbccccccccbbbcbb11111111bf.
            ...fbbfffcccccccbbbb11bc33cccf..
            ..fbbf..cbdbcccccbbb111c131cf...
            ..fff....cbdddddccbbc111c33f....
            ..........ccbddccbbdf1111ff.....
            ............ccfbbbdfccccc.......
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `],
        150,
        true
        )
        projectile = sprites.createProjectileFromSide(img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `, info.score() * 100, randint(0, 160))
        projectile.setPosition(0, randint(0, 160))
        animation.runImageAnimation(
        projectile,
        [img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `,img`
            ..............fffc..............
            ..............fbddcc............
            ..ccc.........ffbddbc...........
            ..cbbc.........fcbbccf..........
            ...cbdc.......ffccccccfffffff...
            ...fbdc....fffcbbbbbbbbbbbbbcff.
            ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
            ....fcdffcccccbbbcbcbbbffbbbbcbf
            ....fcbbccccccbbbcbcbbbff1111bbf
            ...fcbbccccccccbbbcbb11111111bf.
            ...fbbfffcccccccbbbb11bc33cccf..
            ..fbbf..cbdbcccccbbb111c131cf...
            ..fff....cbdddddccbbc111c33f....
            ..........ccbddccbbdf1111ff.....
            ............ccfbbbdfccccc.......
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `],
        150,
        true
        )
        projectile = sprites.createProjectileFromSide(img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `, info.score() * 100, randint(0, 160))
        projectile.setPosition(0, randint(0, 160))
        animation.runImageAnimation(
        projectile,
        [img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `,img`
            ..............fffc..............
            ..............fbddcc............
            ..ccc.........ffbddbc...........
            ..cbbc.........fcbbccf..........
            ...cbdc.......ffccccccfffffff...
            ...fbdc....fffcbbbbbbbbbbbbbcff.
            ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
            ....fcdffcccccbbbcbcbbbffbbbbcbf
            ....fcbbccccccbbbcbcbbbff1111bbf
            ...fcbbccccccccbbbcbb11111111bf.
            ...fbbfffcccccccbbbb11bc33cccf..
            ..fbbf..cbdbcccccbbb111c131cf...
            ..fff....cbdddddccbbc111c33f....
            ..........ccbddccbbdf1111ff.....
            ............ccfbbbdfccccc.......
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `],
        150,
        true
        )
        projectile = sprites.createProjectileFromSide(img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `, info.score() * 100, 0)
        projectile.setPosition(0, randint(0, 160))
        animation.runImageAnimation(
        projectile,
        [img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `,img`
            ..............fffc..............
            ..............fbddcc............
            ..ccc.........ffbddbc...........
            ..cbbc.........fcbbccf..........
            ...cbdc.......ffccccccfffffff...
            ...fbdc....fffcbbbbbbbbbbbbbcff.
            ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
            ....fcdffcccccbbbcbcbbbffbbbbcbf
            ....fcbbccccccbbbcbcbbbff1111bbf
            ...fcbbccccccccbbbcbb11111111bf.
            ...fbbfffcccccccbbbb11bc33cccf..
            ..fbbf..cbdbcccccbbb111c131cf...
            ..fff....cbdddddccbbc111c33f....
            ..........ccbddccbbdf1111ff.....
            ............ccfbbbdfccccc.......
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `],
        150,
        true
        )
        projectile = sprites.createProjectileFromSide(img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `, info.score() * 100, 0)
        projectile.setPosition(0, randint(0, 160))
        animation.runImageAnimation(
        projectile,
        [img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `,img`
            ..............fffc..............
            ..............fbddcc............
            ..ccc.........ffbddbc...........
            ..cbbc.........fcbbccf..........
            ...cbdc.......ffccccccfffffff...
            ...fbdc....fffcbbbbbbbbbbbbbcff.
            ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
            ....fcdffcccccbbbcbcbbbffbbbbcbf
            ....fcbbccccccbbbcbcbbbff1111bbf
            ...fcbbccccccccbbbcbb11111111bf.
            ...fbbfffcccccccbbbb11bc33cccf..
            ..fbbf..cbdbcccccbbb111c131cf...
            ..fff....cbdddddccbbc111c33f....
            ..........ccbddccbbdf1111ff.....
            ............ccfbbbdfccccc.......
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `],
        150,
        true
        )
        projectile = sprites.createProjectileFromSide(img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `, info.score() * 100, 0)
        projectile.setPosition(0, randint(0, 160))
        animation.runImageAnimation(
        projectile,
        [img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `,img`
            ..............fffc..............
            ..............fbddcc............
            ..ccc.........ffbddbc...........
            ..cbbc.........fcbbccf..........
            ...cbdc.......ffccccccfffffff...
            ...fbdc....fffcbbbbbbbbbbbbbcff.
            ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
            ....fcdffcccccbbbcbcbbbffbbbbcbf
            ....fcbbccccccbbbcbcbbbff1111bbf
            ...fcbbccccccccbbbcbb11111111bf.
            ...fbbfffcccccccbbbb11bc33cccf..
            ..fbbf..cbdbcccccbbb111c131cf...
            ..fff....cbdddddccbbc111c33f....
            ..........ccbddccbbdf1111ff.....
            ............ccfbbbdfccccc.......
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `],
        150,
        true
        )
        projectile = sprites.createProjectileFromSide(img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `, info.score() * 100, 0)
        projectile.setPosition(0, randint(0, 160))
        animation.runImageAnimation(
        projectile,
        [img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `,img`
            ..............fffc..............
            ..............fbddcc............
            ..ccc.........ffbddbc...........
            ..cbbc.........fcbbccf..........
            ...cbdc.......ffccccccfffffff...
            ...fbdc....fffcbbbbbbbbbbbbbcff.
            ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
            ....fcdffcccccbbbcbcbbbffbbbbcbf
            ....fcbbccccccbbbcbcbbbff1111bbf
            ...fcbbccccccccbbbcbb11111111bf.
            ...fbbfffcccccccbbbb11bc33cccf..
            ..fbbf..cbdbcccccbbb111c131cf...
            ..fff....cbdddddccbbc111c33f....
            ..........ccbddccbbdf1111ff.....
            ............ccfbbbdfccccc.......
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `],
        150,
        true
        )
        projectile = sprites.createProjectileFromSide(img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `, info.score() * 100, 0)
        projectile.setPosition(0, randint(0, 160))
        animation.runImageAnimation(
        projectile,
        [img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `,img`
            ..............fffc..............
            ..............fbddcc............
            ..ccc.........ffbddbc...........
            ..cbbc.........fcbbccf..........
            ...cbdc.......ffccccccfffffff...
            ...fbdc....fffcbbbbbbbbbbbbbcff.
            ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
            ....fcdffcccccbbbcbcbbbffbbbbcbf
            ....fcbbccccccbbbcbcbbbff1111bbf
            ...fcbbccccccccbbbcbb11111111bf.
            ...fbbfffcccccccbbbb11bc33cccf..
            ..fbbf..cbdbcccccbbb111c131cf...
            ..fff....cbdddddccbbc111c33f....
            ..........ccbddccbbdf1111ff.....
            ............ccfbbbdfccccc.......
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `],
        150,
        true
        )
    }
})
